server:
  port: 8091

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 30000
    lettuce:
      pool:
        max-active: 8  # 最大连接
        max-idle: 8   # 最大空闲连接
        min-idle: 0   # 最小空闲连接
        max-wait: 100ms # 连接等待时间

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml