server:
  port: 8092

redisson:
  singleServerConfig:
    address: "redis://127.0.0.1:6379"
    connectionPoolSize: 10
    connectionMinimumIdleSize: 2

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml