server:
  port: 8093

dubbo:
  application:
    name: user-service-dubbo
    version: 1.0.0
  registry:
    #    address: zookeeper://192.168.228.129:2181
    address: N/A
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.dil.dubbo.api

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml