server:
  port: 8091
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

spring:
  rabbitmq:
    addresses: 192.168.228.129
    port: 5672
    username: root
    password: 1230.0
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个

logging:
  level:
    root: info
  config: classpath:logback-spring.xml